//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mml2vgmIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mml2vgmIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap BreakPoint {
            get {
                object obj = ResourceManager.GetObject("BreakPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap BreakPointMute {
            get {
                object obj = ResourceManager.GetObject("BreakPointMute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccFadeout {
            get {
                object obj = ResourceManager.GetObject("ccFadeout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccFast {
            get {
                object obj = ResourceManager.GetObject("ccFast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccNext {
            get {
                object obj = ResourceManager.GetObject("ccNext", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPause {
            get {
                object obj = ResourceManager.GetObject("ccPause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPlay {
            get {
                object obj = ResourceManager.GetObject("ccPlay", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccPrevious {
            get {
                object obj = ResourceManager.GetObject("ccPrevious", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccSlow {
            get {
                object obj = ResourceManager.GetObject("ccSlow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ccStop {
            get {
                object obj = ResourceManager.GetObject("ccStop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap ClearLog {
            get {
                object obj = ResourceManager.GetObject("ClearLog", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntDescription {
            get {
                return ResourceManager.GetString("cntDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   例外発生:\r\n- Type ------\r\n{0}\r\n- Message ------\r\n{1}\r\n- Source ------\r\n{2}\r\n- StackTrace ------\r\n{3}\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntExceptionFormat {
            get {
                return ResourceManager.GetString("cntExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   内部例外:\r\n- Type ------\r\n{0}\r\n- Message ------\r\n{1}\r\n- Source ------\r\n{2}\r\n- StackTrace ------\r\n{3}\r\n に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntInnerExceptionFormat {
            get {
                return ResourceManager.GetString("cntInnerExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   log.txt に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntLogFilename {
            get {
                return ResourceManager.GetString("cntLogFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting.xml に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntSettingFileName {
            get {
                return ResourceManager.GetString("cntSettingFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   yyyy/MM/dd HH:mm:ss     に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string cntTimeFormat {
            get {
                return ResourceManager.GetString("cntTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon Comp48 {
            get {
                object obj = ResourceManager.GetObject("Comp48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Error {
            get {
                object obj = ResourceManager.GetObject("Error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   .vgm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionVGM {
            get {
                return ResourceManager.GetString("ExtensionVGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .vgz に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionVGZ {
            get {
                return ResourceManager.GetString("ExtensionVGZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .xgm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ExtensionXGM {
            get {
                return ResourceManager.GetString("ExtensionXGM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F01 {
            get {
                object obj = ResourceManager.GetObject("F01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F02 {
            get {
                object obj = ResourceManager.GetObject("F02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F03 {
            get {
                object obj = ResourceManager.GetObject("F03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F04 {
            get {
                object obj = ResourceManager.GetObject("F04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F05 {
            get {
                object obj = ResourceManager.GetObject("F05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F06 {
            get {
                object obj = ResourceManager.GetObject("F06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F07 {
            get {
                object obj = ResourceManager.GetObject("F07", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F08 {
            get {
                object obj = ResourceManager.GetObject("F08", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F09 {
            get {
                object obj = ResourceManager.GetObject("F09", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F10 {
            get {
                object obj = ResourceManager.GetObject("F10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F11 {
            get {
                object obj = ResourceManager.GetObject("F11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap F12 {
            get {
                object obj = ResourceManager.GetObject("F12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon Feli48 {
            get {
                object obj = ResourceManager.GetObject("Feli48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap File {
            get {
                object obj = ResourceManager.GetObject("File", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Filter {
            get {
                object obj = ResourceManager.GetObject("Filter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Folder {
            get {
                object obj = ResourceManager.GetObject("Folder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   JSolo+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF5_JSolo {
            get {
                return ResourceManager.GetString("lblF5_JSolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF5_Play {
            get {
                return ResourceManager.GetString("lblF5_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skip+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF5_Skip {
            get {
                return ResourceManager.GetString("lblF5_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Trace+ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF5_Trace {
            get {
                return ResourceManager.GetString("lblF5_Trace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fade out に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF9_FadeOut {
            get {
                return ResourceManager.GetString("lblF9_FadeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string lblF9_Stop {
            get {
                return ResourceManager.GetString("lblF9_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap LineCursor {
            get {
                object obj = ResourceManager.GetObject("LineCursor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMIDIKB {
            get {
                object obj = ResourceManager.GetObject("planeMIDIKB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap planeMixer {
            get {
                object obj = ResourceManager.GetObject("planeMixer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rec {
            get {
                object obj = ResourceManager.GetObject("rec", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Reload {
            get {
                object obj = ResourceManager.GetObject("Reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFader {
            get {
                object obj = ResourceManager.GetObject("rFader", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_03 {
            get {
                object obj = ResourceManager.GetObject("rFont_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rFont_04 {
            get {
                object obj = ResourceManager.GetObject("rFont_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_04 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_05 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_Font_06 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_Font_06", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap rMIDILCD_KBD_01 {
            get {
                object obj = ResourceManager.GetObject("rMIDILCD_KBD_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   &apos;{{
        ///
        ///	TitleName   =
        ///	TitleNameJ  =
        ///	GameName    =
        ///	GameNameJ   =
        ///	SystemName  =
        ///	SystemNameJ =
        ///	Composer    =
        ///	ComposerJ   =
        ///	ReleaseDate =
        ///	Converted   =
        ///	Notes       =
        ///
        ///	ClockCount  ={0}
        ///
        ///}}
        ///
        ///&apos;Cn1 T{1}
        ///&apos;P01 T{1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string tmpMIDIKbd {
            get {
                return ResourceManager.GetString("tmpMIDIKbd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Warning {
            get {
                object obj = ResourceManager.GetObject("Warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap フェーリ {
            get {
                object obj = ResourceManager.GetObject("フェーリ", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (アイコン) に類似した型 System.Drawing.Icon のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Icon フェーリ48 {
            get {
                object obj = ResourceManager.GetObject("フェーリ48", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
